### ISSUE TITLE
64 bit client update prevents operation.

### ISSUE THREAD

**Issue by wyldlock** [grantoverby/EqOnUbuntu#1]
Hello and thank you for providing this script, it has worked flawlessly for several years. Unfortunately DBG has moved to a 64 bit client version recently. I suspect (but am not adept enough to completely confirm) that the launcher is still 32 bit, as after the game update the launcher would still run, but was unable to start the game. I am not adept enough with WINE to figure out a way to solve this issue if one exists. If you are still interested in maintaining this script and know of a way to make it function, that would be deeply appreciated. If not, thanks for all of the years of play I was able to get out of the game thanks to your work!

**Comment by grantoverby** [comment]
I don't have a bare metal ubuntu install, so I'll need to setup an environment. I probably won't get to that until the weekend.

I'm no wine guru, so no promises. We may have to wait until the wine community addresses it.

**Comment by grantoverby** [comment]
WINEARCH is explicitly set to win32 in lib/vars. This may be as simple as changing that value to win64.

If you would like to test this (I can't atm, see above), follow the instructions in the README, but change all instances of ~/eq to ~/eq64 (or any new directory). You'll need to do a fresh install. Before running ~/eq64/bin/install edit ~/eq64/lib/vars in a texteditor and change win32 to win64.

**Comment by wyldlock** [comment]
Wow, thanks for the quick reply! Unfortunately I am going to be tied down with work for a while, but if I have time after work, I will give it a go. Either way hopefully it will get worked out as this takes my second box offline.

**Comment by grantoverby** [comment]
I updated the code and read me. I figure it's already broken, so what could it hurt...

Hopefully some kind soul will test this for me.

**Comment by wyldlock** [comment]
Looks like I had a corrupt repository problem not related to this script. I have it cleared out for now and it is at least trying to run. Will update as I go.

**Comment by wyldlock** [comment]
Have gotten into the launcher successfully and am patching. More work stuff to do for about an hour. I will update you again, but looks good so far.

**Comment by wyldlock** [comment]
That did the trick once I got the repository thing fixed on my end! Thanks for taking the time!

**Comment by grantoverby** [comment]
Great.

Thanks for opening the issue.
